### ISSUE TITLE
Crash only in Full-Screen mode

### ISSUE THREAD

**Issue by BiNoopsGITHUB** [adamhlt/D3D9-Hook-ImGui#9] opened 2024-10-24 12:46 UTC
![image](https://github.com/user-attachments/assets/c41ec8ab-f976-4e0c-84c5-0b0a70847740)

**Comment by adamhlt** [comment] 2024-10-24 13:24
Without more information, I will not be able to help you.
Did you try to debug your code ?

**Comment by BiNoopsGITHUB** [comment] 2024-10-29 20:55
> Without more information, I will not be able to help you. Did you try to debug your code ?

I haven't changed anything in the code.
I do not know how to debug if it is internal, and I do not understand much, I can only indicate what he will write

**Comment by adamhlt** [comment] 2024-10-30 09:45
Ok, I will try to take a look. Other people reported the same, I will try to investigate it.

**Comment by liyunlong23** [comment] 2024-10-31 05:30
@adamhlt I also encountered such a problem, 1. The original Reset function requires two parameters, not one parameter, 2. Use if you want to reset your rendering device without losing Dear ImGui state.
IMGUI_IMPL_API bool ImGui_ImplDX9_CreateDeviceObjects();
IMGUI_IMPL_API void ImGui_ImplDX9_InvalidateDeviceObjects(); The code is as follows:`HRESULT Hook::hkReset(LPDIRECT3DDEVICE9 pDevice,D3DPRESENT_PARAMETERS* pPresentationParameters)
{
	//Drawing::bSetPos = true;
	//UnHookWindow();
	//Drawing::bInit = FALSE;
	//ImGui_ImplDX9_Shutdown();
	//ImGui_ImplWin32_Shutdown();
	//ImGui::DestroyContext();
	//pDevice = nullptr;
	ImGui_ImplDX9_InvalidateDeviceObjects();
	HRESULT tmpReset = oReset(pDevice,pPresentationParameters);
	ImGui_ImplDX9_CreateDeviceObjects();
	return tmpReset;
}
`

**Comment by liyunlong23** [comment] 2024-10-31 05:45
The above method can solve the problem of full-screen mode and resolution change failure. However, I just found a new problem. After opening the D3D9 application and entering full-screen mode, use alt+tab to switch to the background, open the DLL injection tool, inject the dll into the D3D9 application, and then return to the D3D9 application. I found that IMGUI is displayed normally, but at this time, ALT+TAB cannot switch out of the current D3D9 application. You need to exit the D3D9 application full-screen mode first, and then switch to full-screen mode. ALT+TAB can work normally again and use alt+tab to switch.I have limited time, I hope the author can solve it

**Comment by liyunlong23** [comment] 2024-10-31 06:32
The alt+tab problem mentioned above is caused by creating a D3D device. It can be solved by changing D3DDEVTYPE_HAL  to D3DDEVTYPE_NULLREF. Another beautiful day。

**Comment by adamhlt** [comment] 2024-11-02 15:26
Thanks a lot, I will make some tests when I have free type and give you credits in the readme.

**Comment by adamhlt** [comment] 2024-11-02 17:28
Thanks @liyunlong23, everything is fixed now. I add you in the readme.

**Closed by adamhlt** 2024-11-02 17:28 UTC

**Comment by liyunlong23** [comment] 2024-11-03 02:46
Thank you, it was a very pleasant day
